### ISSUE TITLE
iGenVar - Create first benchmarks for iGenVar

### ISSUE THREAD

**Issue by Irallia** [seqan/iGenVar#122]
- [x] Create an infrastructure for iGenVar benchmarks (add some shell scripts for comprehensibility)
- [x] Run benchmarks for time and space usage
- [x] Compare benchmark results with "truth" and with results of Sniffles (run Sniffles with the same data)

Take data of https://ftp-trace.ncbi.nlm.nih.gov/ReferenceSamples/giab/data/AshkenazimTrio/
