### ISSUE TITLE
iGenVar - Write API & CLI tests for all functions

### ISSUE THREAD

**Issue by Irallia** [seqan/iGenVar#30]
### Write API test for
(Definition of done: when Codecoverage is above ...)
- modules/clustering/hierarchical_clustering_method.hpp
  - [x] partition_junctions()
  - [ ] split_partition_based_on_mate2()
  - [ ] junction_distance()
  - [x] hierarchical_clustering_method()
- modules/clustering/simple_clustering_method.hpp :white_check_mark: #12
  - [x] simple_clustering_method()
- modules/sv_detection_methods/analyze_cigar_method.hpp :white_check_mark: #12
  - [x] analyze_cigar()
- modules/sv_detection_methods/analyze_sa_tag_method.hpp :white_check_mark: #12
  - [x] split_string()
  - [x] retrieve_aligned_segments()
  - [x] analyze_aligned_segments()
  - [x] analyze_sa_tag()  
- structures/... ~#112~
- variant_detection/... ~#112~
- variant_detection/variant_detection.hpp :white_check_mark:
  - [x] detect_junctions_in_long_reads_sam_file
- variant_detection/variant_output.hpp
  - [ ] find_and_output_variants(..., ostream)
  - [ ] find_and_output_variants(..., path)
- variant_parser/variant_record.hpp

### Write CLI tests
- add example data :white_check_mark: #57 
- write tests :white_check_mark: #4 , #69
- Add tests for the help pages. :white_check_mark: #71 

### Implement Code Coverage #118
Resolve App-Template issue https://github.com/seqan/app-template/pull/32 and https://github.com/seqan/app-template/pull/46
-> Codecoverage higher than 85%

**Comment by Irallia** [comment]
![Uploading Bildschirmfoto 2021-05-10 um 21.52.46.png…]()
