### ISSUE TITLE
iGenVar - Call Deletions from long reads

### ISSUE THREAD

**Issue by Irallia** [seqan/iGenVar#32]
**Call SVs:** For larger structural variations, we want to combine the various known methods to call deletions.
- ~~Distinguish between long and short reads in the input #17~~
    - [x] Call Deletions via the CIGAR string
        - [x] Call Deletions in long reads #25 
        - ~~Call Deletions in short reads #27~~
    - [x] Call Deletion using split alignment #18 
- [ ]  Cluster junctions by hierarchical clustering #54

----
EDIT (30.03.2021): We have removed some of the requirements as we are outsourcing them:
- short read input https://github.com/seqan/igenvar/issues/17
