### ISSUE TITLE
iGenVar - Add all Methods of Vaquita

### ISSUE THREAD

**Issue by Irallia** [seqan/iGenVar#84]
Vaquita uses different proofs to detect SVs, we want to reproduce and eventually adopt each method.

- [ ] Cigar String
- [ ] Split read evidence
- [ ] Read pair evidence
- [ ] Read depth evidence
